[services]
gog = True
egs = True
ea_app = True
ubisoft = True
steam = True

[lutris]
library_ignores = 
migration_version = 17
last_library_sync_at = 1781479170
sidebar_collapsed_sections = 
icon_type_gridview_steam = banner
width = 1270
height = 1360
maximized = True
selected_category = service:steam
window_x = 1285
window_y = 29
icon_type_gridview = coverart_med
show_advanced_options = True

