# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# General
set -g default-shell /usr/bin/zsh
set -g history-limit 150000
set -g display-time 4000
set -sg escape-time 0
set -g renumber-windows on
set -g status-position bottom
set -g status-interval 7
set -g status-keys vi
set -g mouse off

# Windows and panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind < swap-window -t -1 \; select-window -t -1
bind > swap-window -t +1 \; select-window -t +1
bind n previous-window
bind p next-window
bind k resize-pane -Z
bind m copy-mode
bind x confirm-before -p "Kill pane? (y/n)" kill-pane
bind r source-file ~/.config/tmux/tmux.conf

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '2'

run '~/.tmux/plugins/tpm/tpm'
